### ISSUE TITLE
Filter "fav.create" and "fav.delete"

### ISSUE THREAD

**Issue by mogita** [LitoMore/fanfou-streamer#2]
## Expected Behavior
Emit `fav` event when anyone favs current user's message.

## Current Behavior
`Fav` events will emit when:
- current user favs a message
- anyone favs current user's message

## Possible Solution
`Fav` events will emit when:
- anyone favs current user's message

## Steps to Reproduce
N/a

## Context (Environment)
N/a

## Detailed Description
N/a

## Possible Implementation
Filter `fav.create` and `fav.delete` events, ignoring all favs triggered by current user, except on his own message (rare though).

**Comment by LitoMore** [comment]
Fixed on #4
